version: "3.8"
services:
  api-gateway:
    build:
      dockerfile: API/src/Gateway/Momentum.Gateway.Api/Dockerfile
      context: .
    image: api-gateway
    container_name: MomentumApiGateway${ENVIRONMENT}
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_ConnectionStrings__Marten=User ID = momentum;Password=momentum123;Server=postgres;Port=5432;Database=momentum_db;Integrated Security=true;Pooling=true
    volumes:
      - ./config/appsettings.json:/app/appsettings.json
      - ./config/appsettings.${ENVIRONMENT}.json:/app/appsettings.${ENVIRONMENT}.json
  postgres:
    image: postgres
    container_name: MomentumPostgres${ENVIRONMENT}
    # Secrets can be hard coded since the DB is not internet facing
    environment:
      - POSTGRES_USER=momentum
      - POSTGRES_PASSWORD=momentum123
      - POSTGRES_DB=momentum_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
  frontend:
    build: 
      dockerfile: Frontend/Dockerfile${ENVIRONMENT}
      context: .
    image: frontend-${ENVIRONMENT_LOWERCASE}
    container_name: MomentumFrontend${ENVIRONMENT}
    volumes: 
    - ./Frontend:/app/src
  proxy:
    image: nginx
    container_name: MomentumReverseProxy${ENVIRONMENT}
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
